base_url = "https://lmntal.github.io//mell-library-examples"
compile_sass = true
title = "mell library examples"
description = "mell library examples"
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
book_number_chapters = true
